spring:
  thymeleaf:
    cache: false
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost/jeju?characterEncoding=utf-8
    username: root
    password: as0109247
    driver-class-name: com.mysql.jdbc.Driver


